// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Avatar field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Fullname field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.fullname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fullname: prismic.KeyTextField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Content for Blog Category documents
 */
interface BlogCategoriesDocumentData {
  /**
   * Name field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_categories.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_categories.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Color field in *Blog Category*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_categories.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoriesDocumentData>,
    "blog_categories",
    Lang
  >;

/**
 * Item in *Blog Post → Publish To*
 */
export interface BlogPostDocumentDataPublishToItem {
  /**
   * Locale field in *Blog Post → Publish To*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: en-US
   * - **API ID Path**: blog_post.publish_to[].locale
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  locale: prismic.SelectField<"en-US" | "ng" | "gh", "filled">;
}

/**
 * Item in *Blog Post → Sources*
 */
export interface BlogPostDocumentDataSourcesItem {
  /**
   * Source Title field in *Blog Post → Sources*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sources[].source_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source_title: prismic.KeyTextField;

  /**
   * Source Description field in *Blog Post → Sources*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sources[].source_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source_description: prismic.KeyTextField;

  /**
   * Source Link field in *Blog Post → Sources*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sources[].source_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  source_link: prismic.LinkField;
}

type BlogPostDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Locale field in *Blog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select what locale you want to publish a content to
   * - **Default Value**: en-US
   * - **API ID Path**: blog_post.locale
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  locale: prismic.SelectField<"en-US" | "ng" | "gh", "filled">;

  /**
   * Publish To field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_to[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publish_to: prismic.GroupField<Simplify<BlogPostDocumentDataPublishToItem>>;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Blog Category field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.blog_category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog_category: prismic.ContentRelationshipField<"blog_categories">;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Reviewer field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.reviewer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  reviewer: prismic.ContentRelationshipField<"reviewer">;

  /**
   * Thumbnail field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Post Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.post_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  post_title: prismic.KeyTextField;

  /**
   * Post Excerpt field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.post_excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  post_excerpt: prismic.RichTextField;

  /**
   * Sources field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sources[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sources: prismic.GroupField<Simplify<BlogPostDocumentDataSourcesItem>>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type PrivacyPolicyDocumentDataSlicesSlice = never;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Published At field in *Privacy Policy*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.published_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_at: prismic.DateField;

  /**
   * Content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

/**
 * Content for Reviewer documents
 */
interface ReviewerDocumentData {
  /**
   * avatar field in *Reviewer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviewer.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Fullname field in *Reviewer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviewer.fullname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fullname: prismic.KeyTextField;
}

/**
 * Reviewer document from Prismic
 *
 * - **API ID**: `reviewer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReviewerDocumentData>,
    "reviewer",
    Lang
  >;

type TermOfUseDocumentDataSlicesSlice = never;

/**
 * Content for Term Of Use documents
 */
interface TermOfUseDocumentData {
  /**
   * Title field in *Term Of Use*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_use.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Published At field in *Term Of Use*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_use.published_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_at: prismic.DateField;

  /**
   * Content field in *Term Of Use*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_use.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Term Of Use*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_use.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TermOfUseDocumentDataSlicesSlice> /**
   * Meta Description field in *Term Of Use*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: term_of_use.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Term Of Use*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: term_of_use.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Term Of Use*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: term_of_use.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Term Of Use document from Prismic
 *
 * - **API ID**: `term_of_use`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermOfUseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TermOfUseDocumentData>,
    "term_of_use",
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | BlogCategoriesDocument
  | BlogPostDocument
  | PrivacyPolicyDocument
  | ReviewerDocument
  | TermOfUseDocument;

/**
 * Primary content in *PostHeader → Primary*
 */
export interface PostHeaderSliceDefaultPrimary {
  /**
   * Publish Date field in *PostHeader → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post_header.primary.publish_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Post Title field in *PostHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your post title
   * - **API ID Path**: post_header.primary.post_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  post_title: prismic.KeyTextField;

  /**
   * Excerpt field in *PostHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_header.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Author field in *PostHeader → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: post_header.primary.author
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Reviewer field in *PostHeader → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: post_header.primary.reviewer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  reviewer: prismic.ContentRelationshipField<"reviewer">;

  /**
   * Thumbnail field in *PostHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_header.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Default variation for PostHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PostHeader*
 */
type PostHeaderSliceVariation = PostHeaderSliceDefault;

/**
 * PostHeader Shared Slice
 *
 * - **API ID**: `post_header`
 * - **Description**: PostHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostHeaderSlice = prismic.SharedSlice<
  "post_header",
  PostHeaderSliceVariation
>;

/**
 * Primary content in *BlogContent → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Blog Content field in *BlogContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.primary.blog_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_content: prismic.RichTextField;
}

/**
 * Default variation for BlogContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogContent*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * BlogContent Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Sources → Items*
 */
export interface SourcesSliceDefaultItem {
  /**
   * Source Title field in *Sources → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sources.items[].source_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  source_title: prismic.RichTextField;

  /**
   * Source Description field in *Sources → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sources.items[].source_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source_description: prismic.KeyTextField;

  /**
   * Source Link field in *Sources → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sources.items[].source_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  source_link: prismic.LinkField;
}

/**
 * Default variation for Sources Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SourcesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SourcesSliceDefaultItem>
>;

/**
 * Slice variation for *Sources*
 */
type SourcesSliceVariation = SourcesSliceDefault;

/**
 * Sources Shared Slice
 *
 * - **API ID**: `sources`
 * - **Description**: Sources
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SourcesSlice = prismic.SharedSlice<
  "sources",
  SourcesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BlogCategoriesDocument,
      BlogCategoriesDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataPublishToItem,
      BlogPostDocumentDataSourcesItem,
      BlogPostDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      ReviewerDocument,
      ReviewerDocumentData,
      TermOfUseDocument,
      TermOfUseDocumentData,
      TermOfUseDocumentDataSlicesSlice,
      AllDocumentTypes,
      PostHeaderSlice,
      PostHeaderSliceDefaultPrimary,
      PostHeaderSliceVariation,
      PostHeaderSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SourcesSlice,
      SourcesSliceDefaultItem,
      SourcesSliceVariation,
      SourcesSliceDefault,
    };
  }
}
