// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  post_header: dynamic(() => import("./PostHeader")),
  rich_text: dynamic(() => import("./BlogContent")),
  sources: dynamic(() => import("./Sources")),
};
